# Generated by Django 3.1.7 on 2021-03-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_restouran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('ingredient', models.CharField(max_length=50)),
                ('meal_type', models.CharField(choices=[('vegan', 'vegan'), ('no_vegan', 'no_vegan')], max_length=50)),
                ('portion', models.CharField(choices=[('1', '1'), ('0.7', '0.7')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_restouran.category')),
            ],
        ),
    ]
