# Generated by Django 3.1.7 on 2021-03-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveIntegerField()),
                ('date_create', models.DateTimeField()),
                ('status', models.CharField(choices=[('in_prossec', 'in_prossec'), ('ready', 'ready'), ('finish', 'finish')], default='in_prossec', max_length=50)),
                ('payment', models.CharField(choices=[('cash', 'cash'), ('card', 'card')], default='cash', max_length=50)),
                ('promocode', models.CharField(max_length=50)),
            ],
        ),
    ]
